# retrieval、multi_agents的结构都可以在这个yaml中修改
# agent和model需要在对应的config文件夹下面修改

defaults:
  - retrieval: text # 改这个可以换text/image，使用retrieval时配置
  - _self_

run-name: mmlb-MDA # 实验名

dataset:
  top_k: 1 # 推理时用top几

retrieval:
  top_k: 10 # 检索时给出top几的结果
  cuda_visible_devices: '0'

mdoc_agent:
  cuda_visible_devices: '0,1,2,3'
  truncate_len: 5 # 用来debug，正常使用时设置为null
  save_freq: 10 # 用来配置保存的频率
  ans_key: ans_${run-name} # predict时生成的答案的key
  save_message: false # 改成true会再记录所有agent的回答

  agents:
    - agent: image_agent # agent用来配置prompt，和控制参考资料中文本/图片的使用
      model: qwen2vl # model用来配置使用的模型
    - agent: text_agent
      model: llama31
    - agent: general_agent
      model: qwen2vl
  
  sum_agent:
    agent: sum_agent # 用来汇总所有agent的回答
    model: qwen2vl

eval_agent: # 用来测试结果
  truncate_len: 5 # 用来debug，正常使用时设置为null
  ans_key: ans_${run-name}
  agent: base
  model: openai